config/routes.rb
Rails.application.routes.draw do
  resources :pants
  resources :shirts
  resources :spotifies
  resources :flipkarts
  resources :fbs
  resources :amazonloginpages
  resources :dells
  resources :iphonemobiles
  resources :lenovos
  resources :skybags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/addresss.rb
class Addresss < ApplicationRecord
  belongs_to :customerr
end
,

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :writer
  has_one :sponsorship
end
,

app/models/customer.rb
# class Customer < ApplicationRecord
# end

app/models/customerr.rb
class Customerr < ApplicationRecord
  has_many :orderrs
  has_one :addresss
end
,

app/models/dell.rb
class Dell < ApplicationRecord
end
,

app/models/fb.rb
class Fb < ApplicationRecord
end
,

app/models/flipkart.rb
class Flipkart < ApplicationRecord
end
,

app/models/iteeem.rb
# class Iteeem < ApplicationRecord
#   belongs_to :orderr
# end

app/models/iteem.rb
class Iteem < ApplicationRecord
  belongs_to :orderr
end
,

app/models/item.rb
# class Item < ApplicationRecord
#   belongs_to :order
# end
#

app/models/itemm.rb
# class Itemm < ApplicationRecord
#   belongs_to:orderrs
# end

app/models/lenovo.rb
class Lenovo < ApplicationRecord
end
,

app/models/order.rb
# class Order < ApplicationRecord
#   belongs_to :item
# end

app/models/orderr.rb
class Orderr < ApplicationRecord
  has_many :iteems
  belongs_to :customerr
end
,

app/models/pant.rb
class Pant < ApplicationRecord
end
,

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :productitems
end
,

app/models/shirt.rb
class Shirt < ApplicationRecord
end
,

app/models/skybag.rb
class Skybag < ApplicationRecord
  validates :name, inclusion: { in: %w(luggagebag clgabg),
    message: "%{value} is not a valid name" }
end
,

app/models/spotify.rb
class Spotify < ApplicationRecord
end
,

app/models/user.rb
class User < ApplicationRecord
end
,

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :sponsorships
  has_many :books, through: :sponsorships
end
,

app/controllers/spotifies_controller.rb
class SpotifiesController < ApplicationController

  def index
    @spotifies=Spotify.all
  end
  def new
    @spotify=Spotify.new
  end
  def create
    @spotify=Spotify.new(spotify_params)
    if @spotify.save
      flash[:notice]="spotify is entered"
      redirect_to spotifies_path
    else
      render 'new '
    end
  end
  private
  def spotify_params
    params.require(:spotify).permit(:gmail, :password)
  end
end
,

app/helpers/spotifies_helper.rb
module SpotifiesHelper
end

app/views/spotifies/_form.html.erb
<%= form_with(model: spotify) do |form| %>
  <% if spotify.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spotify.errors.count, "error") %> prohibited this spotify from being saved:</h2>

      <ul>
        <% spotify.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :gmail, style: "display: block" %>
    <%= form.text_field :gmail %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.number_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spotifies/_spotify.html.erb
<div id="<%= dom_id spotify %>">
  <p>
    <strong>Gmail:</strong>
    <%= spotify.gmail %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= spotify.password %>
  </p>

</div>

app/views/spotifies/edit.html.erb
<h1>Editing spotify</h1>

<%= render "form", spotify: @spotify %>

<br>

<div>
  <%= link_to "Show this spotify", @spotify %> |
  <%= link_to "Back to spotifies", spotifies_path %>
</div>

app/views/spotifies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spotifies</h1>

<div id="spotifies">
  <% @spotifies.each do |spotify| %>
    <%= render spotify %>
    <p>
      <%= link_to "Show this spotify", spotify %>
    </p>
  <% end %>
</div>

<%= link_to "New spotify", new_spotify_path %>

app/views/spotifies/new.html.erb
<h1>New spotify</h1>

<%= render "form", spotify: @spotify %>

<br>

<div>
  <%= link_to "Back to spotifies", spotifies_path %>
</div>

app/views/spotifies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spotify %>

<div>
  <%= link_to "Edit this spotify", edit_spotify_path(@spotify) %> |
  <%= link_to "Back to spotifies", spotifies_path %>

  <%= button_to "Destroy this spotify", @spotify, method: :delete %>
</div>