config/routes.rb
Rails.application.routes.draw do
  resources :pants
  resources :shirts
  resources :spotifies
  resources :flipkarts
  resources :fbs
  resources :amazonloginpages
  resources :dells
  resources :iphonemobiles
  resources :lenovos
  resources :skybags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/addresss.rb
class Addresss < ApplicationRecord
  belongs_to :customerr
end
,

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :writer
  has_one :sponsorship
end
,

app/models/customer.rb
# class Customer < ApplicationRecord
# end

app/models/customerr.rb
class Customerr < ApplicationRecord
  has_many :orderrs
  has_one :addresss
end
,

app/models/dell.rb
class Dell < ApplicationRecord
end
,

app/models/fb.rb
class Fb < ApplicationRecord
end
,

app/models/flipkart.rb
class Flipkart < ApplicationRecord
end
,

app/models/iteeem.rb
# class Iteeem < ApplicationRecord
#   belongs_to :orderr
# end

app/models/iteem.rb
class Iteem < ApplicationRecord
  belongs_to :orderr
end
,

app/models/item.rb
# class Item < ApplicationRecord
#   belongs_to :order
# end
#

app/models/itemm.rb
# class Itemm < ApplicationRecord
#   belongs_to:orderrs
# end

app/models/lenovo.rb
class Lenovo < ApplicationRecord
end
,

app/models/order.rb
# class Order < ApplicationRecord
#   belongs_to :item
# end

app/models/orderr.rb
class Orderr < ApplicationRecord
  has_many :iteems
  belongs_to :customerr
end
,

app/models/pant.rb
class Pant < ApplicationRecord
end
,

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :productitems
end
,

app/models/shirt.rb
class Shirt < ApplicationRecord
end
,

app/models/skybag.rb
class Skybag < ApplicationRecord
  validates :name, inclusion: { in: %w(luggagebag clgabg),
    message: "%{value} is not a valid name" }
end
,

app/models/spotify.rb
class Spotify < ApplicationRecord
end
,

app/models/user.rb
class User < ApplicationRecord
end
,

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :sponsorships
  has_many :books, through: :sponsorships
end
,

app/controllers/dells_controller.rb
class DellsController < ApplicationController

  def index
    @dells=Dell.all
  end

  def new
    @dell=Dell.new
  end
  def create
    @dell=Dell.new(dellnew_params)
    if @dell.save
      flash[:notice]="dell laptop is successfully created"
      redirect_to dells_path
    else
      render 'new'
    end
  end


     private
     def dellnew_params
       params.require(:dell).permit(:name, :ram)
     end
end
,

app/helpers/dells_helper.rb
module DellsHelper
end

app/views/dells/_dell.html.erb
<div id="<%= dom_id dell %>">
  <p>
    <strong>Name:</strong>
    <%= dell.name %>
  </p>

  <p>
    <strong>Ram:</strong>
    <%= dell.ram %>
  </p>

</div>

app/views/dells/_form.html.erb
<%= form_with(model: dell) do |form| %>
  <% if dell.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dell.errors.count, "error") %> prohibited this dell from being saved:</h2>

      <ul>
        <% dell.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :ram, style: "display: block" %>
    <%= form.text_field :ram %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dells/edit.html.erb
<h1>Editing dell</h1>

<%= render "form", dell: @dell %>

<br>

<div>
  <%= link_to "Show this dell", @dell %> |
  <%= link_to "Back to dells", dells_path %>
</div>

app/views/dells/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dells</h1>

<div id="dells">
  <% @dells.each do |dell| %>
    <%= render dell %>
    <p>
      <%= link_to "Show this dell", dell %>
    </p>
  <% end %>
</div>

<%= link_to "New dell", new_dell_path %>

app/views/dells/new.html.erb
<h1>New dell</h1>

<%= render "form", dell: @dell %>

<br>

<div>
  <%= link_to "Back to dells", dells_path %>
</div>

app/views/dells/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dell %>

<div>
  <%= link_to "Edit this dell", edit_dell_path(@dell) %> |
  <%= link_to "Back to dells", dells_path %>

  <%= button_to "Destroy this dell", @dell, method: :delete %>
</div>