config/routes.rb
Rails.application.routes.draw do
  resources :pants
  resources :shirts
  resources :spotifies
  resources :flipkarts
  resources :fbs
  resources :amazonloginpages
  resources :dells
  resources :iphonemobiles
  resources :lenovos
  resources :skybags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/addresss.rb
class Addresss < ApplicationRecord
  belongs_to :customerr
end
,

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :writer
  has_one :sponsorship
end
,

app/models/customer.rb
# class Customer < ApplicationRecord
# end

app/models/customerr.rb
class Customerr < ApplicationRecord
  has_many :orderrs
  has_one :addresss
end
,

app/models/dell.rb
class Dell < ApplicationRecord
end
,

app/models/fb.rb
class Fb < ApplicationRecord
end
,

app/models/flipkart.rb
class Flipkart < ApplicationRecord
end
,

app/models/iteeem.rb
# class Iteeem < ApplicationRecord
#   belongs_to :orderr
# end

app/models/iteem.rb
class Iteem < ApplicationRecord
  belongs_to :orderr
end
,

app/models/item.rb
# class Item < ApplicationRecord
#   belongs_to :order
# end
#

app/models/itemm.rb
# class Itemm < ApplicationRecord
#   belongs_to:orderrs
# end

app/models/lenovo.rb
class Lenovo < ApplicationRecord
end
,

app/models/order.rb
# class Order < ApplicationRecord
#   belongs_to :item
# end

app/models/orderr.rb
class Orderr < ApplicationRecord
  has_many :iteems
  belongs_to :customerr
end
,

app/models/pant.rb
class Pant < ApplicationRecord
end
,

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :productitems
end
,

app/models/shirt.rb
class Shirt < ApplicationRecord
end
,

app/models/skybag.rb
class Skybag < ApplicationRecord
  validates :name, inclusion: { in: %w(luggagebag clgabg),
    message: "%{value} is not a valid name" }
end
,

app/models/spotify.rb
class Spotify < ApplicationRecord
end
,

app/models/user.rb
class User < ApplicationRecord
end
,

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :sponsorships
  has_many :books, through: :sponsorships
end
,

app/controllers/lenovos_controller.rb
class LenovosController < ApplicationController
  def index
    @lenovos=Lenovo.all
  end
  def new
    @lenovo=Lenovo.new
  end
  def create
    @lenovo=Lenovo.new(lenovo_newparams)
     if @lenovo.save
       flash[:notice]="lenovo is successfully is created "
       redirect_to lenovos_path
     else
       render 'new'
     end
   end
   private
   def lenovo_newparams
     params.require(:lenovo).permit(:name, :price)
   end

end
,

app/helpers/lenovos_helper.rb
module LenovosHelper
end

app/views/lenovos/_form.html.erb
<%= form_with(model: lenovo) do |form| %>
  <% if lenovo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lenovo.errors.count, "error") %> prohibited this lenovo from being saved:</h2>

      <ul>
        <% lenovo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lenovos/_lenovo.html.erb
<div id="<%= dom_id lenovo %>">
  <p>
    <strong>Name:</strong>
    <%= lenovo.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= lenovo.price %>
  </p>

</div>

app/views/lenovos/edit.html.erb
<h1>Editing lenovo</h1>

<%= render "form", lenovo: @lenovo %>

<br>

<div>
  <%= link_to "Show this lenovo", @lenovo %> |
  <%= link_to "Back to lenovos", lenovos_path %>
</div>

app/views/lenovos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lenovos</h1>

<div id="lenovos">
  <% @lenovos.each do |lenovo| %>
    <%= render lenovo %>
    <p>
      <%= link_to "Show this lenovo", lenovo %>
    </p>
  <% end %>
</div>

<%= link_to "New lenovo", new_lenovo_path %>

app/views/lenovos/new.html.erb
<h1>New lenovo</h1>

<%= render "form", lenovo: @lenovo %>

<br>

<div>
  <%= link_to "Back to lenovos", lenovos_path %>
</div>

app/views/lenovos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lenovo %>

<div>
  <%= link_to "Edit this lenovo", edit_lenovo_path(@lenovo) %> |
  <%= link_to "Back to lenovos", lenovos_path %>

  <%= button_to "Destroy this lenovo", @lenovo, method: :delete %>
</div>