config/routes.rb
Rails.application.routes.draw do
  resources :pants
  resources :shirts
  resources :spotifies
  resources :flipkarts
  resources :fbs
  resources :amazonloginpages
  resources :dells
  resources :iphonemobiles
  resources :lenovos
  resources :skybags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/addresss.rb
class Addresss < ApplicationRecord
  belongs_to :customerr
end
,

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :writer
  has_one :sponsorship
end
,

app/models/customer.rb
# class Customer < ApplicationRecord
# end

app/models/dell.rb
class Dell < ApplicationRecord
end
,

app/models/fb.rb
class Fb < ApplicationRecord
end
,

app/models/flipkart.rb
class Flipkart < ApplicationRecord
end
,

app/models/iphonemobile.rb
class Iphonemobile < ApplicationRecord
end
,

app/models/iteeem.rb
# class Iteeem < ApplicationRecord
#   belongs_to :orderr
# end

app/models/iteem.rb
class Iteem < ApplicationRecord
  belongs_to :orderr
end
,

app/models/item.rb
# class Item < ApplicationRecord
#   belongs_to :order
# end
#

app/models/itemm.rb
# class Itemm < ApplicationRecord
#   belongs_to:orderrs
# end

app/models/lenovo.rb
class Lenovo < ApplicationRecord
end
,

app/models/order.rb
# class Order < ApplicationRecord
#   belongs_to :item
# end

app/models/orderr.rb
class Orderr < ApplicationRecord
  has_many :iteems
  belongs_to :customerr
end
,

app/models/pant.rb
class Pant < ApplicationRecord
end
,

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :productitems
end
,

app/models/shirt.rb
class Shirt < ApplicationRecord
end
,

app/models/skybag.rb
class Skybag < ApplicationRecord
  validates :name, inclusion: { in: %w(luggagebag clgabg),
    message: "%{value} is not a valid name" }
end
,

app/models/spotify.rb
class Spotify < ApplicationRecord
end
,

app/models/user.rb
class User < ApplicationRecord
end
,

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :sponsorships
  has_many :books, through: :sponsorships
end
,

app/controllers/iphonemobiles_controller.rb
class IphonemobilesController < ApplicationController
  def index
    @iphonemobiles=Iphonemobile.all
  end


  def new
    @iphonemobile=Iphonemobile.new
  end


    def create
      @iphonemobile=Iphonemobile.new(iphonemobile_params)
      if @iphonemobile.save
        flash[:notice]="iphonemobile is successfully created "
        redirect_to iphonemobiles_path
      else
        render 'new '
      end
    end
      private
      def iphonemobile_params
        params.require(:iphonemobile).permit(:name, :price)

      end


end
,

app/helpers/iphonemobiles_helper.rb
module IphonemobilesHelper
end

app/views/iphonemobiles/_form.html.erb
<%= form_with(model: iphonemobile) do |form| %>
  <% if iphonemobile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(iphonemobile.errors.count, "error") %> prohibited this iphonemobile from being saved:</h2>

      <ul>
        <% iphonemobile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/iphonemobiles/_iphonemobile.html.erb
<div id="<%= dom_id iphonemobile %>">
  <p>
    <strong>Name:</strong>
    <%= iphonemobile.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= iphonemobile.price %>
  </p>

</div>

app/views/iphonemobiles/edit.html.erb
<h1>Editing iphonemobile</h1>

<%= render "form", iphonemobile: @iphonemobile %>

<br>

<div>
  <%= link_to "Show this iphonemobile", @iphonemobile %> |
  <%= link_to "Back to iphonemobiles", iphonemobiles_path %>
</div>

app/views/iphonemobiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Iphonemobiles</h1>

<div id="iphonemobiles">
  <% @iphonemobiles.each do |iphonemobile| %>
    <%= render iphonemobile %>
    <p>
      <%= link_to "Show this iphonemobile", iphonemobile %>
    </p>
  <% end %>
</div>

<%= link_to "New iphonemobile", new_iphonemobile_path %>

app/views/iphonemobiles/new.html.erb
<h1>New iphonemobile</h1>

<%= render "form", iphonemobile: @iphonemobile %>

<br>

<div>
  <%= link_to "Back to iphonemobiles", iphonemobiles_path %>
</div>

app/views/iphonemobiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @iphonemobile %>

<div>
  <%= link_to "Edit this iphonemobile", edit_iphonemobile_path(@iphonemobile) %> |
  <%= link_to "Back to iphonemobiles", iphonemobiles_path %>

  <%= button_to "Destroy this iphonemobile", @iphonemobile, method: :delete %>
</div>